/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/madari-theme.ts
 * Command: astryx theme build src/theme/madari-theme.ts
 * CLI: @astryxdesign/cli@0.5.4
 * Core: @astryxdesign/core@0.5.4
 */

/// <reference path="./madari.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const madariTheme: DefinedTheme;
