[package]
name = "madari-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
openapi = ["dep:utoipa"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
utoipa = { workspace = true, optional = true }
