// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ConfigureAddonData, ConfigureAddonErrors, ConfigureAddonResponses, CreateProfileData, CreateProfileErrors, CreateProfileResponses, InstallAddonData, InstallAddonErrors, InstallAddonResponses, LockProfileData, LockProfileErrors, LockProfileResponses, LogoutData, LogoutErrors, LogoutResponses, OverviewData, OverviewErrors, OverviewResponses, PairData, PairErrors, PairResponses, RefreshData, RefreshErrors, RefreshResponses, RemoteData, RemoteErrors, RemoteResponses, RemoveAddonData, RemoveAddonErrors, RemoveAddonResponses, ReorderAddonsData, ReorderAddonsErrors, ReorderAddonsResponses, SelectProfileData, SelectProfileErrors, SelectProfileResponses, SetAddonEnabledData, SetAddonEnabledErrors, SetAddonEnabledResponses, SetPreferencesData, SetPreferencesErrors, SetPreferencesResponses, ShareAddonData, ShareAddonErrors, ShareAddonResponses, UpdateProfileData, UpdateProfileErrors, UpdateProfileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Install an addon from a configured manifest URL
 */
export const installAddon = <ThrowOnError extends boolean = false>(options: Options<InstallAddonData, ThrowOnError>): RequestResult<InstallAddonResponses, InstallAddonErrors, ThrowOnError> => (options.client ?? client).post<InstallAddonResponses, InstallAddonErrors, ThrowOnError>({
    url: '/api/addons',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reorder installed addons for the selected profile
 */
export const reorderAddons = <ThrowOnError extends boolean = false>(options: Options<ReorderAddonsData, ThrowOnError>): RequestResult<ReorderAddonsResponses, ReorderAddonsErrors, ThrowOnError> => (options.client ?? client).put<ReorderAddonsResponses, ReorderAddonsErrors, ThrowOnError>({
    url: '/api/addons/order',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove an addon from the selected profile
 */
export const removeAddon = <ThrowOnError extends boolean = false>(options: Options<RemoveAddonData, ThrowOnError>): RequestResult<RemoveAddonResponses, RemoveAddonErrors, ThrowOnError> => (options.client ?? client).delete<RemoveAddonResponses, RemoveAddonErrors, ThrowOnError>({ url: '/api/addons/{id}', ...options });

/**
 * Reconfigure a shared addon installation
 */
export const configureAddon = <ThrowOnError extends boolean = false>(options: Options<ConfigureAddonData, ThrowOnError>): RequestResult<ConfigureAddonResponses, ConfigureAddonErrors, ThrowOnError> => (options.client ?? client).put<ConfigureAddonResponses, ConfigureAddonErrors, ThrowOnError>({
    url: '/api/addons/{id}/configuration',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Enable or disable an addon for the selected profile
 */
export const setAddonEnabled = <ThrowOnError extends boolean = false>(options: Options<SetAddonEnabledData, ThrowOnError>): RequestResult<SetAddonEnabledResponses, SetAddonEnabledErrors, ThrowOnError> => (options.client ?? client).put<SetAddonEnabledResponses, SetAddonEnabledErrors, ThrowOnError>({
    url: '/api/addons/{id}/enabled',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Link a shared addon installation to another profile
 */
export const shareAddon = <ThrowOnError extends boolean = false>(options: Options<ShareAddonData, ThrowOnError>): RequestResult<ShareAddonResponses, ShareAddonErrors, ThrowOnError> => (options.client ?? client).post<ShareAddonResponses, ShareAddonErrors, ThrowOnError>({
    url: '/api/addons/{id}/share',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Drop the browser session
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>): RequestResult<LogoutResponses, LogoutErrors, ThrowOnError> => (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>({ url: '/api/logout', ...options });

/**
 * Read profiles and the selected profile snapshot
 */
export const overview = <ThrowOnError extends boolean = false>(options?: Options<OverviewData, ThrowOnError>): RequestResult<OverviewResponses, OverviewErrors, ThrowOnError> => (options?.client ?? client).get<OverviewResponses, OverviewErrors, ThrowOnError>({ url: '/api/overview', ...options });

/**
 * Exchange the TV pairing code for a browser token
 */
export const pair = <ThrowOnError extends boolean = false>(options: Options<PairData, ThrowOnError>): RequestResult<PairResponses, PairErrors, ThrowOnError> => (options.client ?? client).post<PairResponses, PairErrors, ThrowOnError>({
    url: '/api/pair',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Replace the selected profile's playback preferences
 */
export const setPreferences = <ThrowOnError extends boolean = false>(options: Options<SetPreferencesData, ThrowOnError>): RequestResult<SetPreferencesResponses, SetPreferencesErrors, ThrowOnError> => (options.client ?? client).put<SetPreferencesResponses, SetPreferencesErrors, ThrowOnError>({
    url: '/api/preferences',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Rename the selected profile or replace its PIN
 */
export const updateProfile = <ThrowOnError extends boolean = false>(options: Options<UpdateProfileData, ThrowOnError>): RequestResult<UpdateProfileResponses, UpdateProfileErrors, ThrowOnError> => (options.client ?? client).patch<UpdateProfileResponses, UpdateProfileErrors, ThrowOnError>({
    url: '/api/profiles',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a profile (a PIN-protected adult is required once one exists)
 */
export const createProfile = <ThrowOnError extends boolean = false>(options: Options<CreateProfileData, ThrowOnError>): RequestResult<CreateProfileResponses, CreateProfileErrors, ThrowOnError> => (options.client ?? client).post<CreateProfileResponses, CreateProfileErrors, ThrowOnError>({
    url: '/api/profiles',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Close the selected profile and relock settings
 */
export const lockProfile = <ThrowOnError extends boolean = false>(options?: Options<LockProfileData, ThrowOnError>): RequestResult<LockProfileResponses, LockProfileErrors, ThrowOnError> => (options?.client ?? client).post<LockProfileResponses, LockProfileErrors, ThrowOnError>({ url: '/api/profiles/lock', ...options });

/**
 * Open a profile for management (its PIN unlocks settings)
 */
export const selectProfile = <ThrowOnError extends boolean = false>(options: Options<SelectProfileData, ThrowOnError>): RequestResult<SelectProfileResponses, SelectProfileErrors, ThrowOnError> => (options.client ?? client).post<SelectProfileResponses, SelectProfileErrors, ThrowOnError>({
    url: '/api/profiles/select',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Send a remote-control key to the TV
 */
export const remote = <ThrowOnError extends boolean = false>(options: Options<RemoteData, ThrowOnError>): RequestResult<RemoteResponses, RemoteErrors, ThrowOnError> => (options.client ?? client).post<RemoteResponses, RemoteErrors, ThrowOnError>({
    url: '/api/remote',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Renew the browser JWT before it expires
 */
export const refresh = <ThrowOnError extends boolean = false>(options?: Options<RefreshData, ThrowOnError>): RequestResult<RefreshResponses, RefreshErrors, ThrowOnError> => (options?.client ?? client).post<RefreshResponses, RefreshErrors, ThrowOnError>({ url: '/api/session/refresh', ...options });
