// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

export type AddonSummary = {
    allow_local: boolean;
    enabled: boolean;
    installation_id: string;
    manifest: Manifest;
};

export type Catalog = {
    extra?: Array<Extra>;
    id: string;
    name?: string | null;
    type: string;
    [key: string]: unknown;
};

export type CreateProfileRequest = {
    kids?: boolean;
    name: string;
    pin?: string;
};

export type Extra = {
    isRequired?: boolean;
    name: string;
    options?: Array<string> | null;
    optionsLimit?: number | null;
};

export type InstallAddonRequest = {
    allow_local?: boolean;
    url: string;
};

/**
 * Opaque identities are scoped to an installation; no implicit cross-provider merge.
 */
export type ItemKey = {
    content_type: string;
    installation_id: string;
    item_id: string;
};

export type LibraryEntry = {
    key: ItemKey;
    metadata?: null | Meta;
    title: string;
};

export type Manifest = {
    addonCatalogs?: Array<Catalog>;
    behaviorHints?: {
        [key: string]: unknown;
    };
    catalogs?: Array<Catalog>;
    id: string;
    idPrefixes?: Array<string> | null;
    name: string;
    resources: Array<ResourceDeclaration>;
    types: Array<string>;
    version: string;
    [key: string]: unknown;
};

export type Meta = {
    id: string;
    name: string;
    type: string;
    videos?: Array<Video>;
    [key: string]: unknown;
};

export type Overview = {
    active_kids?: null | ProfileDto;
    profiles: Array<ProfileDto>;
    selected?: null | ProfileDto;
    snapshot?: null | PublicSnapshot;
};

export type PairRequest = {
    code: string;
};

export type PairResponse = {
    expires_in: number;
    token: string;
};

/**
 * Ordered language preferences are profile-wide; track IDs vary between files.
 */
export type PlaybackPreferences = {
    audio_commentary?: TrackPreference;
    audio_description?: TrackPreference;
    audio_languages?: Array<string>;
    subtitle_forced?: TrackPreference;
    subtitle_languages?: Array<string>;
    subtitle_sdh?: TrackPreference;
    subtitles_enabled?: boolean;
};

/**
 * Public profile fields; `guardian_id` is intentionally not exposed to the browser.
 */
export type ProfileDto = {
    avatar?: string | null;
    id: string;
    kids: boolean;
    name: string;
    pin_protected: boolean;
};

export type Progress = {
    binge_group?: string | null;
    completed: boolean;
    duration_ms?: number | null;
    key: ItemKey;
    metadata?: null | Meta;
    position_ms: number;
    source_provider?: string | null;
    video_id: string;
};

/**
 * Public snapshots omit configured transport URLs. Treat manifest data as untrusted.
 */
export type PublicSnapshot = {
    addons: Array<AddonSummary>;
    api_version: number;
    hidden_continue: Array<ItemKey>;
    library: Array<LibraryEntry>;
    playback_preferences: PlaybackPreferences;
    progress: Array<Progress>;
    revision: number;
};

export type RemoteRequest = {
    command: string;
};

export type RemoteResponse = {
    queued: string;
};

export type ReorderAddonsRequest = {
    ids: Array<string>;
};

export type ResourceDeclaration = string | {
    idPrefixes?: Array<string> | null;
    name: string;
    types?: Array<string>;
    [key: string]: unknown;
};

export type SelectProfileRequest = {
    id: string;
    pin?: string;
};

export type SetEnabledRequest = {
    enabled: boolean;
};

export type ShareAddonRequest = {
    pin?: string;
    target_id: string;
};

export type TrackPreference = 'any' | 'prefer' | 'avoid';

export type UpdateProfileRequest = {
    name: string;
    pin?: string;
};

export type Video = {
    episode?: number | null;
    id: string;
    season?: number | null;
    title?: string | null;
    [key: string]: unknown;
};

export type WebError = {
    error: string;
};

export type InstallAddonData = {
    body: InstallAddonRequest;
    path?: never;
    query?: never;
    url: '/api/addons';
};

export type InstallAddonErrors = {
    401: WebError;
    403: WebError;
    default: WebError;
};

export type InstallAddonError = InstallAddonErrors[keyof InstallAddonErrors];

export type InstallAddonResponses = {
    200: Overview;
};

export type InstallAddonResponse = InstallAddonResponses[keyof InstallAddonResponses];

export type ReorderAddonsData = {
    body: ReorderAddonsRequest;
    path?: never;
    query?: never;
    url: '/api/addons/order';
};

export type ReorderAddonsErrors = {
    401: WebError;
    403: WebError;
    default: WebError;
};

export type ReorderAddonsError = ReorderAddonsErrors[keyof ReorderAddonsErrors];

export type ReorderAddonsResponses = {
    200: Overview;
};

export type ReorderAddonsResponse = ReorderAddonsResponses[keyof ReorderAddonsResponses];

export type RemoveAddonData = {
    body?: never;
    path: {
        /**
         * Addon installation id
         */
        id: string;
    };
    query?: never;
    url: '/api/addons/{id}';
};

export type RemoveAddonErrors = {
    401: WebError;
    403: WebError;
    default: WebError;
};

export type RemoveAddonError = RemoveAddonErrors[keyof RemoveAddonErrors];

export type RemoveAddonResponses = {
    200: Overview;
};

export type RemoveAddonResponse = RemoveAddonResponses[keyof RemoveAddonResponses];

export type ConfigureAddonData = {
    body: InstallAddonRequest;
    path: {
        /**
         * Addon installation id
         */
        id: string;
    };
    query?: never;
    url: '/api/addons/{id}/configuration';
};

export type ConfigureAddonErrors = {
    401: WebError;
    403: WebError;
    default: WebError;
};

export type ConfigureAddonError = ConfigureAddonErrors[keyof ConfigureAddonErrors];

export type ConfigureAddonResponses = {
    200: Overview;
};

export type ConfigureAddonResponse = ConfigureAddonResponses[keyof ConfigureAddonResponses];

export type SetAddonEnabledData = {
    body: SetEnabledRequest;
    path: {
        /**
         * Addon installation id
         */
        id: string;
    };
    query?: never;
    url: '/api/addons/{id}/enabled';
};

export type SetAddonEnabledErrors = {
    401: WebError;
    403: WebError;
    default: WebError;
};

export type SetAddonEnabledError = SetAddonEnabledErrors[keyof SetAddonEnabledErrors];

export type SetAddonEnabledResponses = {
    200: Overview;
};

export type SetAddonEnabledResponse = SetAddonEnabledResponses[keyof SetAddonEnabledResponses];

export type ShareAddonData = {
    body: ShareAddonRequest;
    path: {
        /**
         * Addon installation id
         */
        id: string;
    };
    query?: never;
    url: '/api/addons/{id}/share';
};

export type ShareAddonErrors = {
    401: WebError;
    403: WebError;
    default: WebError;
};

export type ShareAddonError = ShareAddonErrors[keyof ShareAddonErrors];

export type ShareAddonResponses = {
    200: Overview;
};

export type ShareAddonResponse = ShareAddonResponses[keyof ShareAddonResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logout';
};

export type LogoutErrors = {
    401: WebError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    200: unknown;
};

export type OverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/overview';
};

export type OverviewErrors = {
    401: WebError;
};

export type OverviewError = OverviewErrors[keyof OverviewErrors];

export type OverviewResponses = {
    200: Overview;
};

export type OverviewResponse = OverviewResponses[keyof OverviewResponses];

export type PairData = {
    body: PairRequest;
    path?: never;
    query?: never;
    url: '/api/pair';
};

export type PairErrors = {
    401: WebError;
    429: WebError;
    default: WebError;
};

export type PairError = PairErrors[keyof PairErrors];

export type PairResponses = {
    200: PairResponse;
};

export type PairResponse2 = PairResponses[keyof PairResponses];

export type SetPreferencesData = {
    body: PlaybackPreferences;
    path?: never;
    query?: never;
    url: '/api/preferences';
};

export type SetPreferencesErrors = {
    401: WebError;
    403: WebError;
    default: WebError;
};

export type SetPreferencesError = SetPreferencesErrors[keyof SetPreferencesErrors];

export type SetPreferencesResponses = {
    200: Overview;
};

export type SetPreferencesResponse = SetPreferencesResponses[keyof SetPreferencesResponses];

export type UpdateProfileData = {
    body: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/profiles';
};

export type UpdateProfileErrors = {
    401: WebError;
    default: WebError;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
    200: Overview;
};

export type UpdateProfileResponse = UpdateProfileResponses[keyof UpdateProfileResponses];

export type CreateProfileData = {
    body: CreateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/profiles';
};

export type CreateProfileErrors = {
    401: WebError;
    403: WebError;
    default: WebError;
};

export type CreateProfileError = CreateProfileErrors[keyof CreateProfileErrors];

export type CreateProfileResponses = {
    200: Overview;
};

export type CreateProfileResponse = CreateProfileResponses[keyof CreateProfileResponses];

export type LockProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profiles/lock';
};

export type LockProfileErrors = {
    401: WebError;
};

export type LockProfileError = LockProfileErrors[keyof LockProfileErrors];

export type LockProfileResponses = {
    200: Overview;
};

export type LockProfileResponse = LockProfileResponses[keyof LockProfileResponses];

export type SelectProfileData = {
    body: SelectProfileRequest;
    path?: never;
    query?: never;
    url: '/api/profiles/select';
};

export type SelectProfileErrors = {
    401: WebError;
    403: WebError;
    default: WebError;
};

export type SelectProfileError = SelectProfileErrors[keyof SelectProfileErrors];

export type SelectProfileResponses = {
    200: Overview;
};

export type SelectProfileResponse = SelectProfileResponses[keyof SelectProfileResponses];

export type RemoteData = {
    body: RemoteRequest;
    path?: never;
    query?: never;
    url: '/api/remote';
};

export type RemoteErrors = {
    400: WebError;
    401: WebError;
};

export type RemoteError = RemoteErrors[keyof RemoteErrors];

export type RemoteResponses = {
    200: RemoteResponse;
};

export type RemoteResponse2 = RemoteResponses[keyof RemoteResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/session/refresh';
};

export type RefreshErrors = {
    401: WebError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    200: PairResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];
