// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { configureAddon, createProfile, installAddon, lockProfile, logout, type Options, overview, pair, refresh, remote, removeAddon, reorderAddons, selectProfile, setAddonEnabled, setPreferences, shareAddon, updateProfile } from '../sdk.gen';
import type { ConfigureAddonData, ConfigureAddonError, ConfigureAddonResponse, CreateProfileData, CreateProfileError, CreateProfileResponse, InstallAddonData, InstallAddonError, InstallAddonResponse, LockProfileData, LockProfileError, LockProfileResponse, LogoutData, LogoutError, OverviewData, OverviewError, OverviewResponse, PairData, PairError, PairResponse2, RefreshData, RefreshError, RefreshResponse, RemoteData, RemoteError, RemoteResponse2, RemoveAddonData, RemoveAddonError, RemoveAddonResponse, ReorderAddonsData, ReorderAddonsError, ReorderAddonsResponse, SelectProfileData, SelectProfileError, SelectProfileResponse, SetAddonEnabledData, SetAddonEnabledError, SetAddonEnabledResponse, SetPreferencesData, SetPreferencesError, SetPreferencesResponse, ShareAddonData, ShareAddonError, ShareAddonResponse, UpdateProfileData, UpdateProfileError, UpdateProfileResponse } from '../types.gen';

/**
 * Install an addon from a configured manifest URL
 */
export const installAddonMutation = (options?: Partial<Options<InstallAddonData>>): UseMutationOptions<InstallAddonResponse, InstallAddonError, Options<InstallAddonData>> => {
    const mutationOptions: UseMutationOptions<InstallAddonResponse, InstallAddonError, Options<InstallAddonData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await installAddon({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reorder installed addons for the selected profile
 */
export const reorderAddonsMutation = (options?: Partial<Options<ReorderAddonsData>>): UseMutationOptions<ReorderAddonsResponse, ReorderAddonsError, Options<ReorderAddonsData>> => {
    const mutationOptions: UseMutationOptions<ReorderAddonsResponse, ReorderAddonsError, Options<ReorderAddonsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await reorderAddons({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Remove an addon from the selected profile
 */
export const removeAddonMutation = (options?: Partial<Options<RemoveAddonData>>): UseMutationOptions<RemoveAddonResponse, RemoveAddonError, Options<RemoveAddonData>> => {
    const mutationOptions: UseMutationOptions<RemoveAddonResponse, RemoveAddonError, Options<RemoveAddonData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await removeAddon({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Reconfigure a shared addon installation
 */
export const configureAddonMutation = (options?: Partial<Options<ConfigureAddonData>>): UseMutationOptions<ConfigureAddonResponse, ConfigureAddonError, Options<ConfigureAddonData>> => {
    const mutationOptions: UseMutationOptions<ConfigureAddonResponse, ConfigureAddonError, Options<ConfigureAddonData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await configureAddon({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Enable or disable an addon for the selected profile
 */
export const setAddonEnabledMutation = (options?: Partial<Options<SetAddonEnabledData>>): UseMutationOptions<SetAddonEnabledResponse, SetAddonEnabledError, Options<SetAddonEnabledData>> => {
    const mutationOptions: UseMutationOptions<SetAddonEnabledResponse, SetAddonEnabledError, Options<SetAddonEnabledData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await setAddonEnabled({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Link a shared addon installation to another profile
 */
export const shareAddonMutation = (options?: Partial<Options<ShareAddonData>>): UseMutationOptions<ShareAddonResponse, ShareAddonError, Options<ShareAddonData>> => {
    const mutationOptions: UseMutationOptions<ShareAddonResponse, ShareAddonError, Options<ShareAddonData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await shareAddon({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Drop the browser session
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<unknown, LogoutError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<unknown, LogoutError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const overviewQueryKey = (options?: Options<OverviewData>) => createQueryKey('overview', options);

/**
 * Read profiles and the selected profile snapshot
 */
export const overviewOptions = (options?: Options<OverviewData>) => queryOptions<OverviewResponse, OverviewError, OverviewResponse, ReturnType<typeof overviewQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await overview({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: overviewQueryKey(options)
});

/**
 * Exchange the TV pairing code for a browser token
 */
export const pairMutation = (options?: Partial<Options<PairData>>): UseMutationOptions<PairResponse2, PairError, Options<PairData>> => {
    const mutationOptions: UseMutationOptions<PairResponse2, PairError, Options<PairData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await pair({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Replace the selected profile's playback preferences
 */
export const setPreferencesMutation = (options?: Partial<Options<SetPreferencesData>>): UseMutationOptions<SetPreferencesResponse, SetPreferencesError, Options<SetPreferencesData>> => {
    const mutationOptions: UseMutationOptions<SetPreferencesResponse, SetPreferencesError, Options<SetPreferencesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await setPreferences({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Rename the selected profile or replace its PIN
 */
export const updateProfileMutation = (options?: Partial<Options<UpdateProfileData>>): UseMutationOptions<UpdateProfileResponse, UpdateProfileError, Options<UpdateProfileData>> => {
    const mutationOptions: UseMutationOptions<UpdateProfileResponse, UpdateProfileError, Options<UpdateProfileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateProfile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create a profile (a PIN-protected adult is required once one exists)
 */
export const createProfileMutation = (options?: Partial<Options<CreateProfileData>>): UseMutationOptions<CreateProfileResponse, CreateProfileError, Options<CreateProfileData>> => {
    const mutationOptions: UseMutationOptions<CreateProfileResponse, CreateProfileError, Options<CreateProfileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createProfile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Close the selected profile and relock settings
 */
export const lockProfileMutation = (options?: Partial<Options<LockProfileData>>): UseMutationOptions<LockProfileResponse, LockProfileError, Options<LockProfileData>> => {
    const mutationOptions: UseMutationOptions<LockProfileResponse, LockProfileError, Options<LockProfileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await lockProfile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Open a profile for management (its PIN unlocks settings)
 */
export const selectProfileMutation = (options?: Partial<Options<SelectProfileData>>): UseMutationOptions<SelectProfileResponse, SelectProfileError, Options<SelectProfileData>> => {
    const mutationOptions: UseMutationOptions<SelectProfileResponse, SelectProfileError, Options<SelectProfileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await selectProfile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Send a remote-control key to the TV
 */
export const remoteMutation = (options?: Partial<Options<RemoteData>>): UseMutationOptions<RemoteResponse2, RemoteError, Options<RemoteData>> => {
    const mutationOptions: UseMutationOptions<RemoteResponse2, RemoteError, Options<RemoteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await remote({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Renew the browser JWT before it expires
 */
export const refreshMutation = (options?: Partial<Options<RefreshData>>): UseMutationOptions<RefreshResponse, RefreshError, Options<RefreshData>> => {
    const mutationOptions: UseMutationOptions<RefreshResponse, RefreshError, Options<RefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
